import "@stephane888/wbu-atomique/js/bootstrap/all.js";
import "./spa.scss";
//import "./sublime/sublime";
//import "./section/section";
//import "./section-x/section-x"
//import "./section-y/section-y"
//import "./section2/section2"
//import "./produits/produits"
//mport "./galeries/galeries"
import "./sale/sale"
